name: Run Rust Burnout Meter
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

env:
  RUST_BACKTRACE: 1
  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  TWITTER_APP_ACCESS_TOKEN: ${{ secrets.TWITTER_APP_ACCESS_TOKEN }}
  TWITTER_APP_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_APP_ACCESS_TOKEN_SECRET }}
  TWITTER_APP_API_KEY: ${{ secrets.TWITTER_APP_API_KEY }}
  TWITTER_APP_API_SECRET_KEY: ${{ secrets.TWITTER_APP_API_SECRET_KEY }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rust-burnout-meter
        run: |
          # check if the binary exists
          if [ -f target/release/rust-burnout-meter ]; then
            # run the binary, checking if it exits with 0
            if target/release/rust-burnout-meter; then
              echo "Success!"
            else
              echo "Error when running binary"
              exit 1
            fi
            
          else
            echo "Binary not found"
            exit 1
          fi
