name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

env:
  RUST_BACKTRACE: 1
  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  BURNOUT_LIMIT: ${{ secrets.BURNOUT_LIMIT }}
  BURNOUT_DAYS: ${{ secrets.BURNOUT_DAYS }}
  METER_LENGTH: ${{ secrets.METER_LENGTH }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rust-burnout-meter
        run: |
          # check if the binary exists
          if [ -f target/release/rust-burnout-meter-linux ]; then
            # run the binary, checking if it exits with 0
            if target/release/rust-burnout-meter-linux; then
              echo "Success!"
            else
              echo "Error when running binary"
              exit 1
            fi
          else
            echo "Binary not found"
            exit 1
          fi
